# Generated by Django 6.0.2 on 2026-03-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_comentario_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='coment',
            field=models.TextField(verbose_name='Comentario'),
        ),
    ]
